image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
#  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.war
  
docker-build:
  stage: package
  script:
    #- docker build -t registry.gitlab.com/zinab_saadane/petclinic2 .
    #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    #- docker push registry.gitlab.com/zinab_saadane/petclinic2
    - docker build -t $AZURE_REGISTRY/petclinic2-app:latest .
    - docker login -u $AZURE_LOGIN -p $AZURE_PASSWORD $AZURE_REGISTRY
    - docker push $AZURE_REGISTRY/petclinic22-app:latest
