apiVersion: extensions/v1.0.1
kind: Deployment
metadata:
  name: petclinic_zinab 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinic_zinab
    spec:
      containers:
      - name: petclinic_zinab
        image: registry.gitlab.com/zinab_saadane/PETCLINIC2 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com
